const BASE_CRIT_RATE = 0.05;
const BASE_CRIT_DMG = 1.5;
const BASE_COMBO_RATE = 0.05;
const COMBO_HIT_MULTIPLIER = 0.5;
const BASE_MAX_MP = 50;

module.exports = {
    BASE_CRIT_RATE,
    BASE_CRIT_DMG,
    BASE_COMBO_RATE,
    COMBO_HIT_MULTIPLIER,
    BASE_MAX_MP
};
