module.exports = {
  BASE_MAX_STAMINA: 100,
  STA_STAMINA_PER_POINT: 2,
  STAMINA_DRAIN_PER_TRAVEL_HOUR: 8,
  HP_DRAIN_PER_TRAVEL_HOUR_WHEN_STAMINA_ZERO: 2,
  EXHAUSTED_TRAVEL_TIME_MULTIPLIER: 1.35,
  EXHAUSTED_AMBUSH_CHANCE_BONUS: 0.15,
  REST_STAMINA_PER_HOUR_TENT: 25,
  REST_HP_PERCENT_PER_HOUR_TENT: 0.12,
  REST_STAMINA_PER_HOUR_OPEN: 12,
  REST_HP_PERCENT_PER_HOUR_OPEN: 0.05,
  REST_AMBUSH_CHANCE_PER_HOUR_TENT: 0.02,
  REST_AMBUSH_CHANCE_PER_HOUR_OPEN: 0.08,
  MIN_REST_HOURS: 1,
  MAX_REST_HOURS: 8,
  TENT_ITEM_NAME: 'Tenda Sederhana'
};
